name: Setup

description: Setup

inputs:
  node_version:
    description: Node.js version
    required: false
    default: '16'

runs:
  using: composite
  steps:
    - name: Checkout all commits
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: git user config
      shell: bash
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
    - name: Derive appropriate SHAs for base and head for `nx affected` commands
      uses: nrwl/nx-set-shas@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node_version }}
        registry-url: https://registry.npmjs.org
    - name: Install
      shell: bash
      run: npm install
