name: Setup JS

description: Setup JS environment and dependencies

inputs:
  bun_version:
    description: Bun version
    required: false
    default: 1.2.18
  base_ref:
    description: Determines which base SHA to use ('base' for a specific SHA/branch, 'last_successful' for the last successful workflow)
    required: false
    default: base

runs:
  using: composite
  steps:
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ inputs.bun_version }}
    - name: Derive appropriate SHAs for base and head for `nx affected` commands
      uses: nrwl/nx-set-shas@v4
    - name: Derive last successful base SHA for `nx affected` commands
      if: ${{ inputs.base_ref == 'last_successful' }}
      uses: nrwl/nx-set-shas@v4
    - name: Derive base SHA for `nx affected`
      if: ${{ inputs.base_ref == 'base' }}
      shell: bash
      run: |
        echo "NX_BASE=${{ github.event.pull_request.base.sha }}" >> $GITHUB_ENV
        echo "NX_HEAD=${{ github.sha }}" >> $GITHUB_ENV
    - name: Set up bun cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.bun/install/cache
        key: ${{ runner.os }}-bun-${{ inputs.bun_version }}-${{ hashFiles('**/bun.lock', '**/package.json') }}
        restore-keys: |
          ${{ runner.os }}-bun-${{ inputs.bun_version }}-
          ${{ runner.os }}-bun-
    - name: Set up nx cache
      uses: actions/cache@v4
      with:
        path: |
          ${{ github.workspace }}/.nx
          ${{ github.workspace }}/libs/sdk/src/resources/sdk.wasm
        key: ${{ runner.os }}-nx-${{ hashFiles('**/nx.json', '**/package.json', '**/bun.lock', '**/project.json') }}
        restore-keys: |
          ${{ runner.os }}-nx-
    - name: Install Nx globally
      run: bun install -g nx@21.1.3
      shell: bash
    - name: Install JavaScript dependencies
      run: bun install
      shell: bash
