name: Release

description: Version and publish

inputs:
  github_token:
    description: GitHub token
    required: true
  npm_token:
    description: NPM token
    required: true

runs:
  using: composite
  steps:
    - name: Version and publish
      shell: bash
      run: npx nx affected --target=version --base=last-release
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm_token }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
    - name: Tag last-release
      shell: bash
      run: git tag -f last-release
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ inputs.github_token }}
        branch: ${{ github.ref }}
        force: true
        tags: true
