name: Setup Go

description: Setup Go environment and dependencies

inputs:
  go_version:
    description: Go version
    required: false
    default: 1.24.3

runs:
  using: composite
  steps:
    - uses: actions/setup-go@7b8cf10d4e4a01d4992d18a89f4d7dc5a3e6d6f4 # v4.3.0
      with:
        go-version: ${{ inputs.go_version }}
