import { globalCss } from './theme'

export const fontStyles = globalCss({
  '@font-face': [
    // Metropolis
    {
      fontFamily: 'Metropolis',
      src: `url('fonts/Metropolis/metropolis-regular-webfont.woff2') format('woff2'), url('fonts/Metropolis/metropolis-regular-webfont.woff') format('woff')`,
      fontWeight: '400',
      fontStyle: 'normal',
    },
    {
      fontFamily: 'Metropolis',
      src: `url('fonts/Metropolis/metropolis-medium-webfont.woff2') format('woff2'), url('fonts/Metropolis/metropolis-medium-webfont.woff') format('woff')`,
      fontWeight: '500',
      fontStyle: 'normal',
    },
    {
      fontFamily: 'Metropolis',
      src: `url('fonts/Metropolis/metropolis-semibold-webfont.woff2') format('woff2'), url('fonts/Metropolis/metropolis-semibold-webfont.woff') format('woff')`,
      fontWeight: '600',
      fontStyle: 'normal',
    },
    // Inter
    {
      fontFamily: 'Inter',
      fontStyle: 'normal',
      fontWeight: '100 900',
      fontDisplay: 'swap',
      src: `url('fonts/Inter/Inter-roman.var.woff2') format('woff2')`,
      // fontNamedInstance: 'Regular',
    },
    {
      fontFamily: 'Inter',
      fontStyle: 'italic',
      fontWeight: '100 900',
      fontDisplay: 'swap',
      src: `url('fonts/Inter/Inter-italic.var.woff2') format('woff2')`,
      // fontNamedInstance: 'Italic',
    },
    // InterDisplay
    {
      fontFamily: 'InterDisplay',
      fontStyle: 'normal',
      fontWeight: '100 900',
      fontDisplay: 'swap',
      src: `url('fonts/Inter/InterDisplay-roman.var.woff2') format('woff2')`,
      // fontNamedInstance: 'Regular',
    },
    {
      fontFamily: 'InterDisplay',
      fontStyle: 'italic',
      fontWeight: '100 900',
      fontDisplay: 'swap',
      src: `url('fonts/Inter/InterDisplay-italic.var.woff2') format('woff2')`,
      // fontNamedInstance: 'Italic',
    },
    // {
    //   fontFamily: 'Inter',
    //   fontStyle: 'normal',
    //   fontWeight: '100',
    //   src: `url("fonts/Inter/Inter-Thin.woff2") format("woff2"),
    //        url("fonts/Inter/Inter-Thin.woff") format("woff")`,
    // },
    // {
    //   fontFamily: 'Inter',
    //   fontStyle: 'italic',
    //   fontWeight: '100',
    //   src: `url("fonts/Inter/Inter-ThinItalic.woff2") format("woff2"),
    //        url("fonts/Inter/Inter-ThinItalic.woff") format("woff");`,
    // },
    // {
    //   fontFamily: 'Inter',
    //   fontStyle: 'normal',
    //   fontWeight: '200',
    //   src: `url("fonts/Inter/Inter-ExtraLight.woff2") format("woff2"),
    //        url("fonts/Inter/Inter-ExtraLight.woff") format("woff")`,
    // },
    // {
    //   fontFamily: 'Inter',
    //   fontStyle: 'italic',
    //   fontWeight: '200',
    //   src: `url("fonts/Inter/Inter-ExtraLightItalic.woff2") format("woff2"),
    //        url("fonts/Inter/Inter-ExtraLightItalic.woff") format("woff")`,
    // },
    // {
    //   fontFamily: 'Inter',
    //   fontStyle: 'normal',
    //   fontWeight: '300',
    //   src: `url("fonts/Inter/Inter-Light.woff2") format("woff2"),
    //        url("fonts/Inter/Inter-Light.woff") format("woff")`,
    // },
    // {
    //   fontFamily: 'Inter',
    //   fontStyle: 'italic',
    //   fontWeight: '300',
    //   src: `url("fonts/Inter/Inter-LightItalic.woff2") format("woff2"),
    //        url("fonts/Inter/Inter-LightItalic.woff") format("woff")`,
    // },
    // {
    //   fontFamily: 'Inter',
    //   fontStyle: 'normal',
    //   fontWeight: '400',
    //   src: `url("fonts/Inter/Inter-Regular.woff2") format("woff2"),
    //        url("fonts/Inter/Inter-Regular.woff") format("woff")`,
    // },
    // {
    //   fontFamily: 'Inter',
    //   fontStyle: 'italic',
    //   fontWeight: '400',
    //   src: `url("fonts/Inter/Inter-Italic.woff2") format("woff2"),
    //        url("fonts/Inter/Inter-Italic.woff") format("woff")`,
    // },
    // {
    //   fontFamily: 'Inter',
    //   fontStyle: 'normal',
    //   fontWeight: '500',
    //   src: `url("fonts/Inter/Inter-Medium.woff2") format("woff2"),
    //        url("fonts/Inter/Inter-Medium.woff") format("woff")`,
    // },
    // {
    //   fontFamily: 'Inter',
    //   fontStyle: 'italic',
    //   fontWeight: '500',
    //   src: `url("fonts/Inter/Inter-MediumItalic.woff2") format("woff2"),
    //        url("fonts/Inter/Inter-MediumItalic.woff") format("woff")`,
    // },
    // {
    //   fontFamily: 'Inter',
    //   fontStyle: 'normal',
    //   fontWeight: '600',
    //   src: `url("fonts/Inter/Inter-SemiBold.woff2") format("woff2"),
    //        url("fonts/Inter/Inter-SemiBold.woff") format("woff")`,
    // },
    // {
    //   fontFamily: 'Inter',
    //   fontStyle: 'italic',
    //   fontWeight: '600',
    //   src: `url("fonts/Inter/Inter-SemiBoldItalic.woff2") format("woff2"),
    //        url("fonts/Inter/Inter-SemiBoldItalic.woff") format("woff")`,
    // },
    // {
    //   fontFamily: 'Inter',
    //   fontStyle: 'normal',
    //   fontWeight: '700',
    //   src: `url("fonts/Inter/Inter-Bold.woff2") format("woff2"),
    //        url("fonts/Inter/Inter-Bold.woff") format("woff")`,
    // },
    // {
    //   fontFamily: 'Inter',
    //   fontStyle: 'italic',
    //   fontWeight: '700',
    //   src: `url("fonts/Inter/Inter-BoldItalic.woff2") format("woff2"),
    //        url("fonts/Inter/Inter-BoldItalic.woff") format("woff")`,
    // },
    // {
    //   fontFamily: 'Inter',
    //   fontStyle: 'normal',
    //   fontWeight: '800',
    //   src: `url("fonts/Inter/Inter-ExtraBold.woff2") format("woff2"),
    //        url("fonts/Inter/Inter-ExtraBold.woff") format("woff")`,
    // },
    // {
    //   fontFamily: 'Inter',
    //   fontStyle: 'italic',
    //   fontWeight: '800',
    //   src: `url("fonts/Inter/Inter-ExtraBoldItalic.woff2") format("woff2"),
    //        url("fonts/Inter/Inter-ExtraBoldItalic.woff") format("woff")`,
    // },
    // {
    //   fontFamily: 'Inter',
    //   fontStyle: 'normal',
    //   fontWeight: '900',
    //   src: `url("fonts/Inter/Inter-Black.woff2") format("woff2"),
    //        url("fonts/Inter/Inter-Black.woff") format("woff")`,
    // },
    // {
    //   fontFamily: 'Inter',
    //   fontStyle: 'italic',
    //   fontWeight: '900',
    //   src: `url("fonts/Inter/Inter-BlackItalic.woff2") format("woff2"),
    //        url("fonts/Inter/Inter-BlackItalic.woff") format("woff")`,
    // },
    // // InterDisplay
    // {
    //   fontFamily: 'InterDisplay',
    //   fontStyle: 'normal',
    //   fontWeight: '100',
    //   src: `url("fonts/Inter/Inter-Thin.woff2") format("woff2"),
    //        url("fonts/Inter/Inter-Thin.woff") format("woff")`,
    // },
    // {
    //   fontFamily: 'InterDisplay',
    //   fontStyle: 'italic',
    //   fontWeight: '100',
    //   src: `url("fonts/Inter/Inter-ThinItalic.woff2") format("woff2"),
    //        url("fonts/Inter/Inter-ThinItalic.woff") format("woff");`,
    // },
    // {
    //   fontFamily: 'InterDisplay',
    //   fontStyle: 'normal',
    //   fontWeight: '200',
    //   src: `url("fonts/Inter/Inter-ExtraLight.woff2") format("woff2"),
    //        url("fonts/Inter/Inter-ExtraLight.woff") format("woff")`,
    // },
    // {
    //   fontFamily: 'InterDisplay',
    //   fontStyle: 'italic',
    //   fontWeight: '200',
    //   src: `url("fonts/Inter/Inter-ExtraLightItalic.woff2") format("woff2"),
    //        url("fonts/Inter/Inter-ExtraLightItalic.woff") format("woff")`,
    // },
    // {
    //   fontFamily: 'InterDisplay',
    //   fontStyle: 'normal',
    //   fontWeight: '300',
    //   src: `url("fonts/Inter/Inter-Light.woff2") format("woff2"),
    //        url("fonts/Inter/Inter-Light.woff") format("woff")`,
    // },
    // {
    //   fontFamily: 'InterDisplay',
    //   fontStyle: 'italic',
    //   fontWeight: '300',
    //   src: `url("fonts/Inter/Inter-LightItalic.woff2") format("woff2"),
    //        url("fonts/Inter/Inter-LightItalic.woff") format("woff")`,
    // },
    // {
    //   fontFamily: 'InterDisplay',
    //   fontStyle: 'normal',
    //   fontWeight: '400',
    //   src: `url("fonts/Inter/Inter-Regular.woff2") format("woff2"),
    //        url("fonts/Inter/Inter-Regular.woff") format("woff")`,
    // },
    // {
    //   fontFamily: 'InterDisplay',
    //   fontStyle: 'italic',
    //   fontWeight: '400',
    //   src: `url("fonts/Inter/Inter-Italic.woff2") format("woff2"),
    //        url("fonts/Inter/Inter-Italic.woff") format("woff")`,
    // },
    // {
    //   fontFamily: 'InterDisplay',
    //   fontStyle: 'normal',
    //   fontWeight: '500',
    //   src: `url("fonts/Inter/Inter-Medium.woff2") format("woff2"),
    //        url("fonts/Inter/Inter-Medium.woff") format("woff")`,
    // },
    // {
    //   fontFamily: 'InterDisplay',
    //   fontStyle: 'italic',
    //   fontWeight: '500',
    //   src: `url("fonts/Inter/Inter-MediumItalic.woff2") format("woff2"),
    //        url("fonts/Inter/Inter-MediumItalic.woff") format("woff")`,
    // },
    // {
    //   fontFamily: 'InterDisplay',
    //   fontStyle: 'normal',
    //   fontWeight: '600',
    //   src: `url("fonts/Inter/Inter-SemiBold.woff2") format("woff2"),
    //        url("fonts/Inter/Inter-SemiBold.woff") format("woff")`,
    // },
    // {
    //   fontFamily: 'InterDisplay',
    //   fontStyle: 'italic',
    //   fontWeight: '600',
    //   src: `url("fonts/Inter/Inter-SemiBoldItalic.woff2") format("woff2"),
    //        url("fonts/Inter/Inter-SemiBoldItalic.woff") format("woff")`,
    // },
    // {
    //   fontFamily: 'InterDisplay',
    //   fontStyle: 'normal',
    //   fontWeight: '700',
    //   src: `url("fonts/Inter/Inter-Bold.woff2") format("woff2"),
    //        url("fonts/Inter/Inter-Bold.woff") format("woff")`,
    // },
    // {
    //   fontFamily: 'InterDisplay',
    //   fontStyle: 'italic',
    //   fontWeight: '700',
    //   src: `url("fonts/Inter/Inter-BoldItalic.woff2") format("woff2"),
    //        url("fonts/Inter/Inter-BoldItalic.woff") format("woff")`,
    // },
    // {
    //   fontFamily: 'InterDisplay',
    //   fontStyle: 'normal',
    //   fontWeight: '800',
    //   src: `url("fonts/Inter/Inter-ExtraBold.woff2") format("woff2"),
    //        url("fonts/Inter/Inter-ExtraBold.woff") format("woff")`,
    // },
    // {
    //   fontFamily: 'InterDisplay',
    //   fontStyle: 'italic',
    //   fontWeight: '800',
    //   src: `url("fonts/Inter/Inter-ExtraBoldItalic.woff2") format("woff2"),
    //        url("fonts/Inter/Inter-ExtraBoldItalic.woff") format("woff")`,
    // },
    // {
    //   fontFamily: 'InterDisplay',
    //   fontStyle: 'normal',
    //   fontWeight: '900',
    //   src: `url("fonts/Inter/Inter-Black.woff2") format("woff2"),
    //        url("fonts/Inter/Inter-Black.woff") format("woff")`,
    // },
    // {
    //   fontFamily: 'InterDisplay',
    //   fontStyle: 'italic',
    //   fontWeight: '900',
    //   src: `url("fonts/Inter/Inter-BlackItalic.woff2") format("woff2"),
    //        url("fonts/Inter/Inter-BlackItalic.woff") format("woff")`,
    // },
  ],
})
