name: Setup all

description: Setup all

inputs:
  node_version:
    description: Node.js version
    required: false
    default: '20.10.0'
  go_version:
    description: Go version
    required: false
    default: '1.23.0'
  base_ref:
    description: Determines which base SHA to use ('base' for a specific SHA/branch, 'last_successful' for the last successful workflow)
    required: false
    default: base

runs:
  using: composite
  steps:
    - name: Setup Git
      uses: ./.github/actions/setup-git
    - name: Setup JS
      uses: ./.github/actions/setup-js
      with:
        node_version: ${{ inputs.node_version }}
        base_ref: ${{ inputs.base_ref }}
    - name: Setup Go
      uses: ./.github/actions/setup-go
      with:
        go_version: ${{ inputs.go_version }}
