name: Release or Publish
on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/actions/setup
        with:
          node_version: 16
      - name: Workspace lint
        shell: bash
        run: npx nx workspace-lint
      - name: Lint
        shell: bash
        run: npx nx run-many --target=lint --all --parallel=5
      - name: Build
        shell: bash
        # configuration ci will put the dists in each project directory so changesets can publish
        run: npx nx run-many --target=build --configuration=ci --all --parallel=5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONTENT: ${{ github.workspace }}/content/example
      - name: Test
        shell: bash
        run: npx nx run-many --target=test --all --parallel=5
      - name: Create Release Pull Request or Publish to NPM
        uses: changesets/action@v1
        with:
          commit: 'chore: release packages'
          publish: npm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
