name: Release Go modules

concurrency: commits-to-main

on:
  # daily at midnight
  schedule:
    - cron: 0 0 * * *
  # enable manual trigger
  workflow_dispatch:

jobs:
  release-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout all commits
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup
        uses: ./.github/actions/setup
        with:
          node_version: 16
      - name: Release
        run: ./scripts/release-go.sh
      - name: Commit
        shell: bash
        run: |
          # check out the commit as a new branch
          git checkout -b release
          # sync up the main branch in case something has been merged
          # since the action started
          git fetch origin main
          # checkout the main branch and merge in the release branch
          # this will be a fast forward merge unless something went wrong
          git checkout main
          git merge release
          # push the main branch
          git push origin main --tags
          # cleanup
          git branch -D release
