name: Publish containers for frozen explorer branch

on:
  push:
    branches:
      - frozen/explorer

# This is for .npmrc. Nx automatically creates an .npmrc before changesets runs
# and creates one itself, so we need to explicitly have one.
env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

concurrency: commits-to-frozen-explorer

jobs:
  release-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout all commits
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup
        uses: ./.github/actions/setup-all
        with:
          node_version: 20.10.0
          go_version: 1.21.7
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Containers
        shell: bash
        run: npx nx run explorer:container:production-frozen
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Containers zen
        shell: bash
        run: npx nx run explorer:container:production-frozen-testnet-zen
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
